project_id = "ysqnnassgbihnrjkcekb"

[functions.invite-lookup]
verify_jwt = false

[functions.invite-submit]
verify_jwt = false

[functions.invite-submit-new]
verify_jwt = false

[functions.invite-inviter]
verify_jwt = false

[functions.invite-create]
verify_jwt = false

[functions.send-invite-email]
verify_jwt = true

[functions.invite-send-info-email]
verify_jwt = true

[functions.send-invite]
verify_jwt = false
